//========================================================
// 
// 診断画面の2DUI処理[diagnosisui.h]
// Author : Kajino Hiyori
// 
//========================================================
#ifndef _DIAGNOSISUI_H_
#define	_DIAGNOSISUI_H_

#include "resultui.h"

// 診断結果UIの種類
typedef enum
{
	DIAGNOSISTYPE_TITLE = 0,		// 診断結果ロゴ
	DIAGNOSISTYPE_USEDCOMMAND,		// 使われたコマンド
	DIAGNOSISTYPE_R_COMMANDTYPE,	// Rコマンドの種類
	DIAGNOSISTYPE_R_COMMAND100,		// Rコマンド回数[X00]
	DIAGNOSISTYPE_R_COMMAND010,		// Rコマンド回数[0X0]
	DIAGNOSISTYPE_R_COMMAND001,		// Rコマンド回数[00X]
	DIAGNOSISTYPE_R_COMMANDTIMES,	// RXXX回
	DIAGNOSISTYPE_G_COMMANDTYPE,	// Gコマンドの種類
	DIAGNOSISTYPE_G_COMMAND100,		// Gコマンド回数[X00]
	DIAGNOSISTYPE_G_COMMAND010,		// Gコマンド回数[0X0]
	DIAGNOSISTYPE_G_COMMAND001,		// Gコマンド回数[00X]
	DIAGNOSISTYPE_G_COMMANDTIMES,	// GXXX回
	DIAGNOSISTYPE_B_COMMANDTYPE,	// Bコマンドの種類
	DIAGNOSISTYPE_B_COMMAND100,		// Bコマンド回数[X00]
	DIAGNOSISTYPE_B_COMMAND010,		// Bコマンド回数[0X0]
	DIAGNOSISTYPE_B_COMMAND001,		// Bコマンド回数[00X]
	DIAGNOSISTYPE_B_COMMANDTIMES,	// BXXX回
	DIAGNOSISTYPE_Y_COMMANDTYPE,	// Yコマンドの種類
	DIAGNOSISTYPE_Y_COMMAND100,		// Yコマンド回数[X00]
	DIAGNOSISTYPE_Y_COMMAND010,		// Yコマンド回数[0X0]
	DIAGNOSISTYPE_Y_COMMAND001,		// Yコマンド回数[00X]
	DIAGNOSISTYPE_Y_COMMANDTIMES,	// YXXX回
	DIAGNOSISTYPE_MOSTMAGIC,		// 1番使われた魔法
	DIAGNOSISTYPE_MAGICCIRCLE,		// 魔法陣
	DIAGNOSISTYPE_HAPPENDEVENT,		// 発生したイベント数
	DIAGNOSISTYPE_EVENT100,			// イベント数[X00]
	DIAGNOSISTYPE_EVENT010,			// イベント数[0X0]
	DIAGNOSISTYPE_EVENT001,			// イベント数[00X]
	DIAGNOSISTYPE_EVENTTIMES,		// イベントXXX回
	DIAGNOSISTYPE_MAX
}DIAGNOSISTYPE;

// 診断結果UIのテクスチャの種類
typedef enum
{
	DIAGNOSISTEX_TITLE = 0,		// 診断結果ロゴ
	DIAGNOSISTEX_USEDCOMMAND,	// 使われたコマンド数
	DIAGNOSISTEX_R,				// 赤魔法
	DIAGNOSISTEX_G,				// 緑魔法
	DIAGNOSISTEX_B,				// 青魔法
	DIAGNOSISTEX_Y,				// 黄魔法
	DIAGNOSISTEX_MOSTMAGIC,		// 1番使われた魔法
	DIAGNOSISTEX_LEVITATION,	// 浮遊
	DIAGNOSISTEX_COMBUSTION,	// 燃焼
	DIAGNOSISTEX_FLOOD,			// 洪水
	DIAGNOSISTEX_FLASH,			// フラッシュ
	DIAGNOSISTEX_FIREBALL,		// 火球
	DIAGNOSISTEX_SUNSETDELAY,	// 時間停止
	DIAGNOSISTEX_RAINPRAY,		// 雨乞い
	DIAGNOSISTEX_FREEZE,		// 凍結
	DIAGNOSISTEX_GROWTH,		// 成長
	DIAGNOSISTEX_ACCELERATION,	// 加速
	DIAGNOSISTEX_TIMEREVERT,	// 巻き戻し
	DIAGNOSISTEX_HAPPENDEVENT,	// 発生したイベント数
	DIAGNOSISTEX_TIMES,			// 回
	DIAGNOSISTEX_NUMBER,		// 数字
	DIAGNOSISTEX_MAX
}DIAGNOSISTEX;

// プロトタイプ宣言
void InitDiagnosisUI(void);
void UninitDiagnosisUI(void);
void UpdateDiagnosisUI(void);
void DrawDiagnosisUI(void);
void SetDiagnosisUI(void);
DIAGNOSISTEX SetMostMagic(TotalData totalData);
#endif
